###########
##Options##
###########
setting:
##Should we display messages to console?
    debug: false

##Should we overwrite this config if there's an update to it?
    update_overwrite: true
    
##Announce debugs to admins? headhunter.admin permission node.
##Can be turned on temporarily with the /headhunteradmin debug command
    debugtoadmins: false

##Should the heads emit particles? Not yet implemented.
    particles: true

##Should we announce to all players when a player has found all heads? 
    announcefindingall: true

##How often should we save the head data? (in minutes)
##Heads are also saved when a player leaves the server.
##Only players that have found any heads are saved.
    autosaveinterval: 15

##How long ago should a player have logged in before we purge their data? (Months)
##0 = never purge.
    purgeafter: 0

##Do you need the headhunter.basic permission to unlock heads?
    huntingrequiresperm: false

##How many players should our top list store? -- Stored in Heads.yml
##
    topamountsaved: 20
    
##Should we run commands when heads are found (if a command is set?
##These commands are run from console.
    commandOnHeadFound: true

############
##Messages##
############
messages:
##What should the plugins prefix be?
    prefix: "&3[&bHeadHunter&3] "
##How should we announce a player that has found all skulls?
##Announcefindingall must be set to true.
##<found>, <max>, <playername>
    announcefindingallmessage: "&6<playername>&f has found all &c<max>&f heads!"

##What should we tell a player that is hunting for heads?
##<found>, <max>, <playername>, <idfound>, <headname>
    countmessage: "&aYou just found &f<headname>&a. In total you have found &6<found>&f/<max> &aheads."
    countcommandmessage: "&aYou have found &6<found>&a out of &6<max>&a heads."
    
##What should we tell a player that already found a head?
##<found>, <max>, <playername>
    repeatmessage: "&aYou have already found this head."

