name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
api-version: 1.16
main: ${mainClass}

commands:
    headhunter:
        description: An example command
        permission: headhunter.basic
        usage: /<command>
        aliases: hh
    headhunteradmin:
        description: An example command
        permission: headhunter.admin
        usage: /<command>
        aliases: hha

permissions:
    headhunter.basic:
        description: "Allows you to count the heads you find, if enabled in config."
        default: op
    headhunter.admin:
        description: "Allows you to edit heads, and savings."
        default: op